language: java
jdk:
  - oraclejdk7
  - openjdk6
before_install:
  - apt-get install python-setuptools
  - easy_install pygments
script: "gradle build"
notifications:
    email:
        recipients:
            - chico.sokol@gmail.com
        on_success: change
        on_failure: always
