language: java
jdk:
  - oraclejdk7
  - openjdk6
script: "gradle build"
notifications:
    email:
        recipients:
            - chico.sokol@gmail.com
        on_success: change
        on_failure: always
